adminGalerie:
    path:     /
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:index" }

adminGalerie_show:
    path:     /{id}/show
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:show" }

adminGalerie_new:
    path:     /new
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:new" }

adminGalerie_create:
    path:     /create
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:create" }
    requirements: { _method: post }

adminGalerie_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:edit" }

adminGalerie_update:
    path:     /{id}/update
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:update" }
    requirements: { _method: post|put }

adminGalerie_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteFrontendBundle:GalerieAdmin:delete" }
    requirements: { _method: post|delete }
