adminArticles:
    path:     /
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:index" }

adminArticles_show:
    path:     /{id}/show
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:show" }

adminArticles_new:
    path:     /new
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:new" }

adminArticles_create:
    path:     /create
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:create" }
    requirements: { _method: post }

adminArticles_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:edit" }

adminArticles_update:
    path:     /{id}/update
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:update" }
    requirements: { _method: post|put }

adminArticles_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiteFrontendBundle:ArticleAdmin:delete" }
    requirements: { _method: post|delete }
