<?php

namespace Site\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function offreALaUne(){
        $offset = 0 ;
        $limit =  3;
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.id','DESC')
         ->setFirstResult($offset)
         ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function findAllOffre(){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.id','DESC');

        return $qb->getQuery()->getResult();
    }
}
