<?php

namespace Site\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends EntityRepository
{
    public function clientBy(){
        $offset = 0 ;
        $limit =  4;
        $qb = $this->createQueryBuilder('a')
            ->where("a.consulter = 0")
            ->orderBy('a.id','DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function clientNotifBy(){
        $qb = $this->createQueryBuilder("a")
            ->where("a.consulter = 0");

        return $qb->getQuery()->getResult();
    }

    public function clientNotifModif($id){
        $query = $this->_em->createQuery("UPDATE Site\FrontendBundle\Entity\Clients c SET c.consulter = '1' WHERE c.id = :id" ) ;
        $query->setParameter('id' , $id) ;
        return $query->execute() ;
    }



}
