<?php

namespace Site\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends EntityRepository
{
    public function findAllGalerie(){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.id','DESC');

        return $qb->getQuery()->getResult();
    }
}
