<?php

namespace Site\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NiveauxEtudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauxEtudesRepository extends EntityRepository
{
}
